### ISSUE TITLE
writing to LiquidTemp.sensor

### ISSUE THREAD

**Issue by Brelade** [Naata/Trinket-M0-liquid-temperature-sensor#1]
All is configured correctly (temp shows up in serial) but the powershell script does not write to LiquidTemp.sensor, nor does the FanControl plugin work.

**Comment by Naata** [comment]
Hi, thanks for cloning repo :-) can you make sure that ps script is using the same com port as serial reader?

**Comment by Brelade** [comment]
As far as I'm aware it is. Using COM5
