### ISSUE TITLE
crazy temperature

### ISSUE THREAD

**Issue by 0rsa** [Naata/Trinket-M0-liquid-temperature-sensor#3]
Hello,

I'm using a Trinket M0 with a Barrow G1/4" 10K Temperature Sensor Stop Fitting

When the sensor is not mounted, the temperature reported by the FanControl's plugin is about 31°C

When I plug the sensor to 4 - GND, the temperature becomes crazy, the LED turns pink and I can read more than 300°C in FanControl

![image](https://github.com/Naata/Trinket-M0-liquid-temperature-sensor/assets/769750/870c25be-8358-4173-9598-caa1dfcf1995)

Do you have any idea of what could be wrong?

**Comment by Naata** [comment]
Unfortunately not, broken sensor maybe?

**Comment by 0rsa** [comment]
I tried with a corsair temperature sensor and same result :-/

**Comment by Naata** [comment]
Maybe these are different thermistor types - there are NTC and PTC. I think I used PTC but not sure now as my WC setup is disassembled.

**Comment by micah686** [comment]
I found this on reddit and tested it, and I verified that it works:

> So, I got impatient. Grabbed a 10k Ohm resistor and connected 3V3 with A4. Worked instantly. So any pin of the probe to either GND and A4, and 10k Ohm between 3V3 and A4. If you don't have 10k Ohm, anything near that will work, if you change the value of the resistor in the sketch.

https://www.reddit.com/r/watercooling/comments/r5jvt8/comment/jgow0gh/?utm_source=share&utm_medium=web2x&context=3

set the `#define SERIESRESISTOR #######` to the resistance of your resistor. So if you have a 10K resistor, set it to 10000. I had a 15K resistor, so I set it to 15000.

Doing that made it change from wildly fluctuating to a stable value.
